Refactor build process in GitHub Actions workflow by removing unnecessary package installations and improving error handling for binary execution

diff --git a/.github/workflows/debian_build.yml b/.github/workflows/debian_build.yml
--- a/.github/workflows/debian_build.yml
+++ b/.github/workflows/debian_build.yml
@@ -26,17 +26,16 @@ jobs:
       - name: Build Lunati
         run: |
           apt-get update
-          apt-get install -y tree git g++ make libc6-dev cmake libpng-dev libjpeg-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext libsdl2-dev
+          apt-get install -y tree git g++ make libc6-dev cmake libpng-dev libjpeg-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev
           git clone --depth 1 https://github.com/safwanehfaz/luanti.git
           cd luanti
-          cmake . \
-          -DBUILD_SERVER=TRUE \
-          -DBUILD_CLIENT=FALSE \
-          -DCMAKE_BUILD_TYPE=Release \
-          -DRUN_IN_PLACE=TRUE
-          make -j$(nproc)
-          tree
-          ./bin/luanti --run-unittests
+          cmake . -DBUILD_SERVER=TRUE -DBUILD_CLIENT=FALSE -DCMAKE_BUILD_TYPE=Release -DRUN_IN_PLACE=TRUE
+          make -j$(nproc) || exit 1
+          if [ ! -x ./bin/luanti ]; then
+              echo 'luanti binary not found or not executable!'
+              exit 127
+          fi
+         ./bin/luanti --run-unittests
       
       # Step 4: Pack the files into a .deb archive
       - name: Build .deb File
